### ISSUE TITLE
Where is the -∀ symbol?

### ISSUE THREAD

**Issue by trlef19** [DenverCoder1/LaTeX-Gboard-Dictionary#17]
There is a -∃ symbol (  ∄) but not the equivalent one for the ∀ symbol.

**Comment by DenverCoder1** [comment]
There isn't a "not for all" symbol in Unicode, so it's not possible for one to be added to the Gboard dictionary. See [Mathematical Operators (Unicode Block)](https://en.m.wikipedia.org/wiki/Mathematical_Operators_(Unicode_block)).

My only suggestion is using `\lnot \forall` for ¬∀ instead.
