### ISSUE TITLE
Add unicode fraction symbols

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/LaTeX-Gboard-Dictionary#32]
The following fraction symbols are missing from the dictionary.

Please see the formatting guidelines explained in #5 to contribute!

- ½ `\frac12`
- ⅓ `\frac13`
- ⅔ `\frac23`
- ¼ `\frac14`
- ¾ `\frac34`
- ⅕ `\frac15`
- ⅖ `\frac25`
- ⅗ `\frac35`
- ⅘ `\frac45`
- ⅙ `\frac16`
- ⅚ `\frac56`
- ⅛ `\frac18`
- ⅜ `\frac38`
- ⅝ `\frac58`
- ⅞ `\frac78`

**Comment by parthpanchal123** [comment]
I'll take this up!

**Comment by DenverCoder1** [comment]
@parthpanchal123 Great! If you have any questions feel free to ask!

**Comment by parthpanchal123** [comment]
Opened a PR  #35
