### ISSUE TITLE
Add zodiac signs

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/LaTeX-Gboard-Dictionary#33]
The following zodiac and astronomy symbols can be added to the dictionary.

Please see the formatting guidelines explained in #5 to contribute!

Feel free to add one or more that are missing.

**Zodiac**

- \aries: `♈︎`
- \taurus: `♉︎`
- \gemini: `♊︎`
- \cancer: `♋︎`
- \leo: `♌︎`
- \virgo: `♍︎`
- \libra: `♎︎`
- \scorpio: `♏︎`
- \sagittarius: `♐︎`
- \capricorn: `♑︎`
- \aquarius: `♒︎`
- \pisces: `♓︎`

**Astronomy**

- \sun: `☉`
- \moon: `☾`
- \mercury: `☿`
- \venus: `♀`
- \earth: `⊕`
- \mars: `♂`
- \ceres: `⚳`
- \jupiter: `♃`
- \saturn: `♄`
- \uranus: `♅`
- \neptune: `♆`
- \pluto: `♇`

**Comment by adityagi02** [comment]
I'll work on it

**Comment by Yugal41735** [comment]
is this issue still open?
