### ISSUE TITLE
Subscript and superscript

### ISSUE THREAD

**Issue by AlexandreHDK** [DenverCoder1/LaTeX-Gboard-Dictionary#71]
Hello, I tried without sucess these 4 symbols: +=()
I think they are well used as subscript and superscript

**Comment by DenverCoder1** [comment]
See #13. They were removed since they don't work as Gboard shortcuts.

There are alternatives that exist already:

```
_plus	₊	
^plus	⁺	
_minus	₋	
^minus	⁻	
_eq	₌	
^eq	⁼	
^lp	⁽	
^rp	⁾	
_lp	₍	
_rp	₎	
```
